version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: legalApp-backend
    restart: always
    env_file:
      - .env
    environment:
      - PORT=${PORT}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '${PORT}:${PORT}'
    networks:
      - legalApp_network
    volumes:
      - .:/app
      - /app/node_modules

  postgres:
    container_name: legalApp-postgres
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '6543:5432'
    networks:
      - legalApp_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 5
      timeout: 3s

volumes:
  pg_data:

networks:
  legalApp_network: